service: commandeer-tanks

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  region: us-east-1
  stage: ${opt:stage, 'development'}
  timeout: 30
  versionFunctions: false

plugins:
  - serverless-dynamo-stream-plugin
  - serverless-plugin-typescript
  - serverless-localstack

functions:
  tankHandler: ${file(./handlers/tankHandler.yml):tankHandler}

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
